# Generated by Django 3.2.5 on 2021-12-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('limit', models.CharField(max_length=32)),
                ('read_last', models.DateTimeField(auto_now_add=True, verbose_name='阅读时间')),
            ],
        ),
    ]
