# Generated by Django 3.2.5 on 2021-12-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiYun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('one', models.CharField(max_length=32)),
                ('two', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg_money', models.CharField(max_length=60)),
                ('manage', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=60)),
                ('recruit', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ZhiXiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=32)),
                ('beifen', models.CharField(max_length=32)),
                ('guangfen', models.CharField(max_length=32)),
                ('shangfen', models.DateTimeField(max_length=32)),
                ('shenfen', models.DateTimeField(max_length=32)),
                ('sufen', models.DateTimeField(max_length=32)),
                ('tianfen', models.DateTimeField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
